
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL'
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET'

export const REVIEW_UPDATE_REQUEST = 'REVIEW_UPDATE_REQUEST'
export const REVIEW_UPDATE_SUCCESS = 'REVIEW_UPDATE_SUCCESS'
export const REVIEW_UPDATE_FAIL = 'REVIEW_UPDATE_FAIL'
export const REVIEW_UPDATE_RESET = 'REVIEW_UPDATE_RESET'

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST'
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS'
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL'
export const REVIEW_DELETE_RESET = 'REVIEW_DELETE_RESET'


export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const GET_MY_REVIEWS_REQUEST = 'GET_MY_REVIEWS_REQUEST'
export const GET_MY_REVIEWS_SUCCESS = 'GET_MY_REVIEWS_SUCCESS'
export const GET_MY_REVIEWS_FAIL = 'GET_MY_REVIEWS_FAIL'

export const GET_REVIEW_REQUEST = 'GET_REVIEW_REQUEST'
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS'
export const GET_REVIEW_FAIL = 'GET_REVIEW_FAIL'


export const UP_VOTE_REQUEST = 'UP_VOTE_REQUEST'
export const UP_VOTE_SUCCESS = 'UP_VOTE_SUCCESS'
export const UP_VOTE_FAIL = 'UP_VOTE_FAIL'
export const UP_VOTE_RESET = 'UP_VOTE_RESET'